apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-profile
  labels:
    app: mysql-profile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-profile
  template:
    metadata:
      labels:
        app: mysql-profile
    spec:
      containers:
      - name: database-profile
        image: mysql
        resources:
          requests:
            memory: 0.6Gi
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: testpassword
        livenessProbe:
          tcpSocket:
            port: 3306
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: database-profile
          # /var/lib/mysql 是MySQL的資料存放點
          mountPath: "/var/lib/mysql"
      volumes:
      - name: database-profile
        persistentVolumeClaim:
          claimName: database-profile