apiVersion: v1
kind: Pod
metadata:
  name: gateway-pod
  labels:
    app: gateway-pod
spec:
  containers:
  - name: pod-gateway
    image: daychen/gateway:v2.0.1
    ports:
    - containerPort: 9090
      name: web
    env:
    - name: RABBITMQ_HOST
      value: rabbitmq
    - name: REPORTING_HOST
      value: jaeger-agent
    - name: JWT_SECRET
      value: "<QR7{:Y#Ounvd(w=^sBqG7roW<d_GgS3[X6r,m@H=$KOyh9&4X"