apiVersion: v1
kind: Pod
metadata:
  name: gateway-pod
  labels:
    app: gateway-pod
spec:
  containers:
  - name: pod-gateway
    image: daychen/gateway:v1.4.1
    ports:
    - containerPort: 9090
      name: web
    env:
    - name: RABBITMQ_HOST
      value: rabbitmq
    - name: REPORTING_HOST
      value: jaeger-agent