apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-ipfs
  labels:
    app: go-ipfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-ipfs
  template:
    metadata:
      labels:
        app: go-ipfs
    spec:
      containers:
      - name: go-ipfs
        image: "ipfs/go-ipfs:master"
        command: ["/usr/local/bin/start_ipfs"]
        ports:
        - containerPort: 4001
          name: "swarm"
          protocol: "TCP"
        - containerPort: 5001
          name: "api"
          protocol: "TCP"
