apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: item-service
  template:
    metadata:
      labels:
        app: item-service
    spec:
      containers:
      - name: pod-item-service
        image: daychen/item-service:v2.3.1
        env:
        - name: RABBITMQ_HOST
          value: rabbitmq
        - name: MYSQL_HOST
          value: mysql-item
