apiVersion: v1
kind: PersistentVolume
metadata:
  name: file-volume
  labels:
    volume: file-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/docker/k8s-volume/sqlite-file"  