kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: file-volume
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      volume: file-volume