apiVersion: v1
kind: PersistentVolume
metadata:
  name: database
  labels:
    volume: item-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/docker/k8s-volume/mysql-item"  