apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-service
  template:
    metadata:
      labels:
        app: profile-service
    spec:
      containers:
      - name: pod-profile-service
        image: daychen/profile-service:v2.3.1
        env:
        - name: RABBITMQ_HOST
          value: rabbitmq
        - name: MYSQL_HOST
          value: mysql-profile
