apiVersion: apps/v1
kind: Deployment
metadata:
  name: rent-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rent-service
  template:
    metadata:
      labels:
        app: rent-service
    spec:
      containers:
      - name: pod-rent-service
        image: daychen/rent-service:v2.2.0
        env:
        - name: RABBITMQ_HOST
          value: rabbitmq
