
swagger: "2.0"

info:
  title: "租賃系統"
  version: "1.0"
host: localhost

tags:
  - name: 個人資料
    description: 點數紀錄與租借紀錄查詢
  - name: 物品
    description: 物品資料
  - name: 使用者
    description: 使用者相關
  - name: JWT Authentication
    description: authentication
paths:
  /profile/:
    get:
      tags:
      - 個人資料
      # security:
      #   - jwt: []
      summary: '個人資料、點數紀錄與租借紀錄'
      responses:
        '200':
          description: '取得個人紀錄'
          schema:
            type: object
            properties:
              point:
                type: integer
                example: 10
              lends:
                type: array
                items:
                  $ref: '#/definitions/LentItems'
              returns:
                type: array
                items:
                  $ref: '#/definitions/LentItems'

  /items/:
    get:
      tags: 
      - 物品
      summary: '列出所有物品、分類與數量'
      responses:
        '200':
          description: 'Fetch a list of items'
          schema:
            type: array
            items:
              $ref: '#/definitions/Items'
  /items/get-category/:
    get:
      tags: 
      - 物品
      summary: '分類'
      x-swagger-router-controller: api.items
      operationId: get_category
      responses:
        '200':
          description: 'create category'
          schema:
            type: array
            items:
              $ref: '#/definitions/ItemCategory'
  /items/create-category/:
    post:
      tags: 
      - 物品
      summary: '新增分類'
      x-swagger-router-controller: api.items
      operationId: create_category
      parameters:
        - in: body
          name: data
          description: 'Create category'
          required: true
          schema:
            $ref: '#/definitions/ItemCategory'
      responses:
        '201':
          description: 'create category'
  /auth/:
    post:
      tags:
      - JWT Authentication
      summary: 'Get access token'
      parameters:
        - in: body
          name: data
          description: 'Get access token'
          required: true
          schema:
            $ref: '#/definitions/Account'
      responses:
        '200':
          description: 'get token'
        '400':
          description: 'Miss'
        '401':
          description: 'Error username or password'
  /auth/create-user/:
    post:
      tags:
        - JWT Authentication
      summary: '註冊新帳號'
      x-swagger-router-controller: api.auth
      operationId: create_user
      parameters:
        - in: body
          name: data
          description: 'Create user'
          required: true
          schema:
            $ref: '#/definitions/Account'
      responses:
        '201':
          description: 'create user'



securityDefinitions:
  jwt:
    type: apiKey
    name: Authorization
    in: header
    x-authentication-scheme: Bearer


definitions:
  ItemCategory:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
        example: 文具用品
  Items:
    type: object
    properties:
      id:
        type: integer
        format: int64
      category:
        $ref: '#/definitions/ItemCategory'
      name: 
        type: string
        example: 剪刀
      amount:
        type: integer
        example: 5
  LentItems:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name: 
        type: string
        example: 剪刀

  Account:
    type: object
    required:
      - username
      - password
    properties:
      username:
        type: string
      password:
        type: string

      
      
