
swagger: "2.0"

info:
  title: "租賃系統"
  version: "1.0"
# host: lab.daychen.tw

securityDefinitions:
  Jwt:
    type: apiKey
    name: Authorization
    in: header

tags:
  - name: 個人資料
    description: 點數紀錄與租借紀錄查詢
  - name: 物品
    description: 物品資料
  - name: 使用者
    description: 使用者相關
  - name: JWT Authentication
    description: authentication
paths:
  /profile/:
    get:
      tags:
      - 個人資料
      # security:
        # - Jwt: []
      summary: '個人資料、點數紀錄與租借紀錄'
      responses:
        '200':
          description: '取得個人紀錄'
          schema:
            type: object
            properties:
              point:
                type: integer
                example: 10
              lends:
                type: array
                items:
                  $ref: '#/definitions/LentItems'

  /items/:
    get:
      tags: 
      - 物品
      summary: '列出所有物品、分類與數量'
      responses:
        '200':
          description: 'Fetch a list of items'
          schema:
            type: array
            items:
              $ref: '#/definitions/Items'
  /items/image/{item_id}:
    get:
      tags:
      - 物品
      summary: '取得物品圖片'
      x-swagger-router-controller: api.items
      operationId: "get_item_image"
      parameters:
      - name: item_id
        in: path
        required: true
        type: string
        format: path
      responses:
        '200':
          description: 'Fetch a image of item'
  /items/create/:
    post:
      tags:
      - 物品
      summary: '新增物品'
      description: "新增物品"
      x-swagger-router-controller: api.items
      operationId: "create_item"
      consumes:
      - multipart/form-data
      parameters:
      - in: formData
        name: image
        description: The file to be uploaded
        type: file
      - in: formData
        name: categoryname
        type: string
        required: true
      - in: formData
        name: name
        type: string
        required: true
      responses:
        '200':
          description: 'Fetch item'
  /items/get-category/:
    get:
      tags: 
      - 物品
      summary: '分類'
      x-swagger-router-controller: api.items
      operationId: get_category
      responses:
        '200':
          description: 'create category'
          schema:
            type: array
            items:
              $ref: '#/definitions/ItemCategory'
  /items/rent/:
    post:
      tags:
      - 物品
      summary: '租借物品'
      x-swagger-router-controller: api.items
      operationId: rent
      parameters:
        - in: body
          name: data
          description: "物品編號"
          required: true
          schema:
            type: object
            properties:
              item_id:
                type: integer
                format: int64

      responses:
        '200':
          description: '租借物品'
          schema:
            type: object
            properties:
              message:
                type: string
  /items/return/:
    post:
      tags:
      - 物品
      summary: 歸還物品
      x-swagger-router-controller: api.items
      operationId: returned
      parameters:
        - in: body
          name: data
          description: "物品編號"
          required: true
          schema:
            type: object
            properties:
              lend_id:
                type: integer
                format: int64
      responses:
        '200':
          description: '歸還物品'
          schema:
            type: object
            properties:
              message:
                type: string
  # /items/create-category/:
  #   post:
  #     tags: 
  #     - 物品
  #     summary: '新增分類'
  #     x-swagger-router-controller: api.items
  #     operationId: create_category
  #     parameters:
  #       - in: body
  #         name: data
  #         description: 'Create category'
  #         required: true
  #         schema:
  #           type: object
  #           properties:
  #             name:
  #               type: string
  #     responses:
  #       '201':
  #         description: 'create category'
  /auth/:
    post:
      tags:
      - JWT Authentication
      summary: 'Get access token'
      parameters:
        - in: body
          name: data
          description: 'Get access token'
          required: true
          schema:
            $ref: '#/definitions/Account'
      responses:
        '200':
          description: 'get token'
        '400':
          description: 'Miss'
        '401':
          description: 'Error username or password'
  /auth/create-user/:
    post:
      tags:
        - JWT Authentication
      summary: '註冊新帳號'
      x-swagger-router-controller: api.auth
      operationId: create_user
      parameters:
        - in: body
          name: data
          description: 'Create user'
          required: true
          schema:
            $ref: '#/definitions/Account'
      responses:
        '201':
          description: 'create user'

definitions:
  ItemCategory:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
        example: 文具用品
  Items:
    type: object
    properties:
      id:
        type: integer
        format: int64
      category-id:
        type: integer
        format: int64
      name: 
        type: string
        example: 剪刀
      amount:
        type: integer
        example: 5
  LentItems:
    type: object
    properties:
      id:
        type: integer
        format: int64
      item_id:
        type: integer
        format: int64
      name: 
        type: string
        example: 剪刀
      return:
        type: boolean
        example: false

  Account:
    type: object
    required:
      - username
      - password
    properties:
      username:
        type: string
      password:
        type: string

      
      
