
swagger: "2.0"

info:
  title: "練習 Python Microservice"
  version: "1.0"
host: localhost

tags:
  - name: 書籍
    description: 書籍資料
  - name: 商城
    description: 連接線上書籍商城資料
  - name: 使用者
    description: 使用者相關
  - name: JWT Authentication
    description: authentication
paths:
  /books/:
    get:
      tags: 
      - 書籍
      summary: '列出所有書籍與書籍分類'
      responses:
        '200':
          description: 'Fetch a list of books'
          schema:
            type: array
            items:
              $ref: '#/definitions/Books'
    post:
      tags:
      - 書籍
      summary: '新增書籍'
      parameters:
        - in: body
          name: data
          description: Book object that needs to be added to the store
          required: true
          schema:
            $ref: '#/definitions/InsertBook'
      responses:
        '201':
          description: "insert success"
        '405':
          description: Invalid input
  /auth/:
    post:
      tags:
      - JWT Authentication
      summary: 'Get access token'
      parameters:
        - in: body
          name: data
          description: 'Get access token'
          required: true
          schema:
            $ref: '#/definitions/Account'
      responses:
        '200':
          description: 'get token'
        '400':
          description: 'Miss'
        '401':
          description: 'Error username or password'



securityDefinitions:
  jwt:
    type: apiKey
    name: Authorization
    in: header
    x-authentication-scheme: Bearer


definitions:
  BookCategory:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
        example: "微服務"
  InsertBook:
    type: object
    required:
      - name
      - amount
    properties:
      category:
        type: integer
        format: int64
      name: 
        type: string
        example: Python 微服務
      amount:
        type: integer
  Books:
    type: object
    properties:
      category:
        type: string
        example: 微服務
      name: 
        type: string
        example: Python 微服務
      amount:
        type: integer
  Account:
    type: object
    required:
      - username
      - password
    properties:
      username:
        type: string
      password:
        type: string

      
      
