apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbimq-volume
  labels:
    volume: rabbitmq-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/app/data/rabbitmq"