kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: database-item
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      volume: item-volume